/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator */

#ifndef _Included_Calculator
#define _Included_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator
 * Method:    factorial
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Calculator_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
