[package]
name = "meu_uuid"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.9"
uuid = { version = "1.3", features = ["v4"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
