[package]
name = "grpc_tarefas"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tonic-build = "0.8"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1", features = ["macros","rt-multi-thread"] }
