# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tarefa_pb2 as tarefa__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tarefa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TarefaServiceStub(object):
    """Serviço de gerenciamento de tarefas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listar = channel.unary_unary(
                '/tarefa.TarefaService/Listar',
                request_serializer=tarefa__pb2.ListaTarefasRequest.SerializeToString,
                response_deserializer=tarefa__pb2.ListaTarefasResponse.FromString,
                _registered_method=True)
        self.Criar = channel.unary_unary(
                '/tarefa.TarefaService/Criar',
                request_serializer=tarefa__pb2.CriarTarefaRequest.SerializeToString,
                response_deserializer=tarefa__pb2.Tarefa.FromString,
                _registered_method=True)


class TarefaServiceServicer(object):
    """Serviço de gerenciamento de tarefas
    """

    def Listar(self, request, context):
        """Retorna todas as tarefas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Criar(self, request, context):
        """Adiciona uma tarefa e devolve a criada
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TarefaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listar': grpc.unary_unary_rpc_method_handler(
                    servicer.Listar,
                    request_deserializer=tarefa__pb2.ListaTarefasRequest.FromString,
                    response_serializer=tarefa__pb2.ListaTarefasResponse.SerializeToString,
            ),
            'Criar': grpc.unary_unary_rpc_method_handler(
                    servicer.Criar,
                    request_deserializer=tarefa__pb2.CriarTarefaRequest.FromString,
                    response_serializer=tarefa__pb2.Tarefa.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarefa.TarefaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarefa.TarefaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TarefaService(object):
    """Serviço de gerenciamento de tarefas
    """

    @staticmethod
    def Listar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/Listar',
            tarefa__pb2.ListaTarefasRequest.SerializeToString,
            tarefa__pb2.ListaTarefasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Criar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/Criar',
            tarefa__pb2.CriarTarefaRequest.SerializeToString,
            tarefa__pb2.Tarefa.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
