# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\x12\x06tarefa\":\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x11\n\tconcluida\x18\x03 \x01(\x08\"\x15\n\x13ListaTarefasRequest\"7\n\x14ListaTarefasResponse\x12\x1f\n\x07tarefas\x18\x01 \x03(\x0b\x32\x0e.tarefa.Tarefa\"\'\n\x12\x43riarTarefaRequest\x12\x11\n\tdescricao\x18\x01 \x01(\t2\x89\x01\n\rTarefaService\x12\x43\n\x06Listar\x12\x1b.tarefa.ListaTarefasRequest\x1a\x1c.tarefa.ListaTarefasResponse\x12\x33\n\x05\x43riar\x12\x1a.tarefa.CriarTarefaRequest\x1a\x0e.tarefa.Tarefab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFA']._serialized_start=24
  _globals['_TAREFA']._serialized_end=82
  _globals['_LISTATAREFASREQUEST']._serialized_start=84
  _globals['_LISTATAREFASREQUEST']._serialized_end=105
  _globals['_LISTATAREFASRESPONSE']._serialized_start=107
  _globals['_LISTATAREFASRESPONSE']._serialized_end=162
  _globals['_CRIARTAREFAREQUEST']._serialized_start=164
  _globals['_CRIARTAREFAREQUEST']._serialized_end=203
  _globals['_TAREFASERVICE']._serialized_start=206
  _globals['_TAREFASERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
